naver:
  client:
    clientId: mUbbqbhhwqaTiIMCJUJB
    clientSecret: K1uKIz4Vsu
    accessTokenUri: https://nid.naver.com/oauth2.0/token
    userAuthorizationUri: https://nid.naver.com/oauth2.0/authorize
    tokenName: oauth_token
    authenticationScheme: header
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://openapi.naver.com/v1/nid/me

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=ORACLE;DATABASE_TO_UPPER=FALSE
    username: sa
    password:

mybatis:
  type-aliases-package: com.john.cena.model
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true